; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal]

; Profiles


; Modules
projects[ctools]
projects[libraries]
projects[pathauto]
projects[token]
projects[transliteration]
projects[variable]
projects[nodereference_url]
projects[rules]
projects[backup_migrate]
projects[content_access]

;jQuery
projects[jquery_update]

;Feeds
projects[feeds]

;Site export Modules
projects[features]
projects[strongarm]

;Theme manipulation
projects[sweaver]

;SEO related Modules
projects[globalredirect]
projects[page_title]
projects[xmlsitemap]

projects[panels]
projects[ds]

projects[google_analytics]

;Views and related Modules
projects[views]
projects[eva]
projects[views_bulk_operations]
projects[views_slideshow]


;form related Modules
projects[webform]
projects[mollom]


;map related Modules
;projects[location]
;projects[gmap]

;Text management
projects[wysiwyg]

;Image management
projects[media]
projects[filefield_sources]
projects[image_resize_filter]
projects[insert]
projects[imce]
projects[imce_wysiwyg]
projects[lightbox2]
projects[colorbox]
projects[colorbox_node]

;Media management
projects[emfield]
projects[media_vimeo]
projects[media_youtube]

;Date Modules
projects[date]

;Development
projects[devel]
projects[coder]
projects[less]


;cck
projects[link]
project[email]

;Internationalization
projects[i18n]
projects[transliteration]


;Other Modules
projects[fontyourface]
projects[quicktabs]
projects[nodequeue]
projects[mailchimp]
projects[profile2]


; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
; TinyMCE 3.5.x
libraries[tinymce][download][type] = get
libraries[tinymce][download][url] = http://github.com/downloads/tinymce/tinymce/tinymce_3.5.6.zip

; CKEditor 3.6.2
;libraries[ckeditor][download][type] = get
;libraries[ckeditor][download][url] = http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.4/ckeditor_3.6.4.zip

;Less php
libraries[lessphp][download][type] = git
libraries[lessphp][download][url] = http://github.com/leafo/lessphp
